all:
  vars:
    bastion_ip: 84.201.134.130
    bastion_user: ubuntu
    bastion_ssh: ~/.ssh/id_rsa_ya

    node_ssh: ~/.ssh/id_rsa_ya
    nodes_ssh_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ bastion_ip }} -i ~/.ssh/id_rsa_ya"'

    cp1_ip: 192.168.10.26
    cp1_user: ubuntu

    node1_ip: 192.168.20.27
    node1_user: ubuntu

    node2_ip: 192.168.30.12
    node2_user: ubuntu

    node3_ip: 192.168.40.16
    node3_user: ubuntu
  hosts:
    bastion_vm:
      ansible_host: "{{ bastion_ip }}"
      ip: "{{ bastion_ip }}"
      access_ip: "{{ bastion_ip }}"
      ansible_user: "{{ bastion_user }}"
      ansible_ssh_private_key_file: "{{ bastion_ssh }}"
    cp1:
      ansible_host: "{{ cp1_ip }}"
      ip: "{{ cp1_ip }}"
      access_ip: "{{ cp1_ip }}"
      ansible_user: "{{ cp1_user }}"
      ansible_ssh_private_key_file: "{{ node_ssh }}"
      ansible_ssh_common_args: "{{ nodes_ssh_args }}"
    node1:
      ansible_host: "{{ node1_ip }}"
      ip: "{{ node1_ip }}"
      access_ip: "{{ node1_ip }}"
      ansible_user: "{{ node1_user }}"
      ansible_ssh_private_key_file: "{{ node_ssh }}"
      ansible_ssh_common_args: "{{ nodes_ssh_args }}"
    node2:
      ansible_host: "{{ node2_ip }}"
      ip: "{{ node2_ip }}"
      access_ip: "{{ node2_ip }}"
      ansible_user: "{{ node2_user }}"
      ansible_ssh_private_key_file: "{{ node_ssh }}"
      ansible_ssh_common_args: "{{ nodes_ssh_args }}"
    node3:
      ansible_host: "{{ node3_ip }}"
      ip: "{{ node3_ip }}"
      access_ip: "{{ node3_ip }}"
      ansible_user: "{{ node3_user }}"
      ansible_ssh_private_key_file: "{{ node_ssh }}"
      ansible_ssh_common_args: "{{ nodes_ssh_args }}"
  children:
    bastion:
      hosts:
        bastion_vm:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
